name: Run compose

on: push

jobs:
  run-test:
    name: run compose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Start containers
        run: docker-compose version
